Parse fields as aeson values
mlabs-haskell/csv-aeson pull request #1
Opened 2023-02-10 17:50 UTC by cortsf

2023-02-15 13:02 UTC, errfrom requested changes

2023-02-15 13:02 UTC, errfrom commented on Text/CSV/Aeson.hs
> +  many1 digit >>= pure . Number . read
```suggestion
parseInt = Number . read <$> many1 digit
```

2023-02-15 13:02 UTC, errfrom commented on Text/CSV/Aeson.hs
> +  pure $ Number (fromFloatDigits (read (num <> "." <> dec) :: Double))
Is there a reason why we don't parse the value to a `Scientific` directly?

Before:
```
ghci> parse parseReal "" "1000.123456789123456789"
Right (Number 1000.1234567891235)
```
After:
```
ghci> parse parseReal "" "1000.123456789123456789"
Right (Number 1000.123456789123456789)
```
```suggestion
  pure $ Number $ read $ num <> "." <> dec
```

2023-02-15 13:02 UTC, errfrom commented on Text/CSV/Aeson.hs
> +  string "null" >> pure Null
```suggestion
parseNull = string "null" $> Null
```

2023-02-15 13:02 UTC, errfrom commented on Text/CSV/Aeson.hs
> +  many (noneOf ",\n\r\"") >>= pure . String . T.pack
```suggestion
parseString = String . T.pack <$> many (noneOf ",\n\r\"")
```

2023-02-15 13:09 UTC, errfrom commented
I don't know the exact requirements, but perhaps we should consider handling `Bool`s as well?

2023-02-15 13:16 UTC, errfrom commented on Text/CSV/Aeson.hs
> +record = (try parseReal <|> try parseInt <|>  try parseNull <|> parseQuotedString <|> parseString) `sepBy` char ','
Redundant space
```suggestion
record = (try parseReal <|> try parseInt <|> try parseNull <|> parseQuotedString <|> parseString) `sepBy` char ','
```

2023-02-15 19:41 UTC, nalane requested changes
The types should never be converted from Strings. They need to remain as strings so that they can be spliced into the final JSON

2023-02-21 17:27 UTC, nalane commented
This PR is probably no longer needed, right? @cortsf

2023-02-21 17:58 UTC, cortsf commented
> This PR is probably no longer needed, right? @cortsf

Yes, we are not using this repo anymore.

2023-02-21 18:16 UTC, closed without merging

2023-02-21 18:17 UTC, nalane commented
In that case, I'll go ahead and delete this repo, unless you think it might be good to keep around for any reason

2023-02-21 18:23 UTC, cortsf commented
> In that case, I'll go ahead and delete this repo, unless you think it might be good to keep around for any reason

I can't see any reason to keep it. It would be quite rare that somebody could need something like this.

2023-02-21 18:24 UTC, cortsf commented
I'll keep a copy just in case (?)